// checksum 0x9a77 version 0x30001
/*
  This file was generated by the Mobile Qt Application wizard of Qt Creator.
  MainWindow is a convenience class containing mobile device specific code
  such as screen orientation handling.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include "game.h"

#include <QMainWindow>

namespace Ui {
    class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT
public:
    explicit MainWindow(QWidget *parent = 0);
    virtual ~MainWindow();

private slots:
    void startResetGame();
    void updateRemainingTime(int seconds);
    void updateScore(int score);
    void checkBox1();
    void checkBox2();
    void checkBox3();
    void checkBox4();
    void updateToNextTask();
    void openScoreList(int score = 0);

private:
    Ui::MainWindow *ui;
    Game m_game;
};

#endif // MAINWINDOW_H
